### 텐서플로 2.0 시작하기: 초보자용
- TensorFlow 설정하기

In [1]:
import tensorflow as tf
print("TensorFlow version: ", tf.__version__)

TensorFlow version:  2.14.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


11490434/11490434 [==============================] - 1s 0us/step


In [3]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[0.10852847, 0.08282852, 0.07281455, 0.12810078, 0.03243439,
        0.08736372, 0.1081352 , 0.13685814, 0.09202977, 0.15090643]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.10080276, 0.09824514, 0.09726623, 0.10279515, 0.09341685,
        0.09869172, 0.10076313, 0.10369931, 0.0991533 , 0.10516639]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.3157542

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


c:\Users\h\anaconda3\Lib\site-packages\keras\src\backend.py:5729: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


1875/1875 [==============================] - 5s 2ms/step - loss: 0.2984 - accuracy: 0.9135
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1454 - accuracy: 0.9571
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1078 - accuracy: 0.9682
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0873 - accuracy: 0.9729
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0743 - accuracy: 0.9763


In [10]:
model.fit(x_train, y_train, epochs=5)

model.evaluate(x_test,  y_test, verbose=2)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0657 - accuracy: 0.9793
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0588 - accuracy: 0.9816
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0524 - accuracy: 0.9828
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0490 - accuracy: 0.9842
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0465 - accuracy: 0.9847
313/313 - 1s - loss: 0.0723 - accuracy: 0.9787 - 504ms/epoch - 2ms/step


[0.07232198864221573, 0.9786999821662903]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.0853375 , 0.0853375 , 0.08533754, 0.08534248, 0.0853375 ,
        0.0853375 , 0.0853375 , 0.23195718, 0.08533751, 0.08533771],
       [0.08533677, 0.08533685, 0.23196901, 0.0853368 , 0.08533677,
        0.08533677, 0.08533677, 0.08533677, 0.08533677, 0.08533677],
       [0.08533914, 0.23193166, 0.08534405, 0.08533926, 0.08533921,
        0.08533914, 0.08533949, 0.08534566, 0.08534332, 0.08533913],
       [0.23193447, 0.08533895, 0.08534934, 0.08533895, 0.08533897,
        0.08533946, 0.08533933, 0.08533898, 0.08533895, 0.08534261],
       [0.08534078, 0.08534076, 0.08534081, 0.08534076, 0.23190577,
        0.08534076, 0.0853408 , 0.08534314, 0.08534077, 0.08536566]],
      dtype=float32)>