### Scikit-Learn overview
##### Iris classification - Decision Tree

1. Data Preprocessing

In [37]:
import sklearn
sklearn.__version__

'1.3.0'

In [38]:
from sklearn.datasets import load_iris
iris = load_iris()

In [39]:
# Accessing Iris data
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [40]:
# data - X (sl, sw, pl, pw)
iris.data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [41]:
# feature_names - X names
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [42]:
# target - y
iris.target[-5:]


array([2, 2, 2, 2, 2])

In [43]:
# target_names - y names
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [44]:
import pandas as pd
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [45]:
df['species'] = iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0

In [46]:
# Shape of X and y
iris.data.shape, iris.target.shape

((150, 4), (150,))

In [47]:
# Destribution
df.species.value_counts()

species
0    50
1    50
2    50
Name: count, dtype: int64

In [48]:
# Description - DESCR
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [49]:
# Summarize
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)     species  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

##### 2. Splitting into training and testing data

In [50]:
from sklearn.model_selection import train_test_split
import numpy as np

In [51]:
X_train, X_test, y_train, y_test = train_test_split(
    iris.data, iris.target, random_state=2023
)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((112, 4), (38, 4), (112,), (38,))

In [52]:
# unique함수는 넘파이 배열에서 중복된 값들을 제거한 배열을 반환해줍니다.
# return_counts 파라미터를 True로 지정하면, 중복되지 않은 값들이 각각 몇 번씩 등장하는지의 빈도를 함께 반환해줍니다.
np.unique(y_train, return_counts=True), np.unique(y_test, return_counts=True)

((array([0, 1, 2]), array([34, 37, 41], dtype=int64)),
 (array([0, 1, 2]), array([16, 13,  9], dtype=int64)))

In [53]:
# y 값의 분포를 균일하게
X_train, X_test, y_train, y_test = train_test_split(
    iris.data, iris.target, stratify=iris.target, random_state=2023
)
np.unique(y_train, return_counts=True), np.unique(y_test, return_counts=True)

((array([0, 1, 2]), array([37, 37, 38], dtype=int64)),
 (array([0, 1, 2]), array([13, 13, 12], dtype=int64)))

In [54]:
# 학습 데이터와 테스트 데이터의 비율(test_size)
X_train, X_test, y_train, y_test = train_test_split(
    iris.data, iris.target, stratify=iris.target, test_size=0.2, random_state=2023
)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [55]:
np.unique(y_train, return_counts=True)

(array([0, 1, 2]), array([40, 40, 40], dtype=int64))

##### 3. Training

In [58]:
# Decision tree model
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'random_state': None,
 'splitter': 'best'}

In [59]:
dtc.fit(X_train, y_train)

DecisionTreeClassifier()

##### 4. Prediction

In [60]:
pred = dtc.predict(X_test)

In [62]:
rf = pd.DataFrame({'Real': y_test, 'Pred': pred})
rf.head()

Real  Pred
0     2     2
1     0     0
2     1     1
3     1     1
4     0     0

In [63]:
X_test[:5]

array([[6.3, 3.3, 6. , 2.5],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 2.5, 3. , 1.1],
       [5.9, 3. , 4.2, 1.5],
       [4.6, 3.6, 1. , 0.2]])

##### 5. Evaluation

In [64]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.9666666666666667

In [65]:
dtc.score(X_test, y_test)

0.9666666666666667