### Bag of Words
##### 1. CountVectorizer

In [1]:
text = 'My wife likes to watch baseball games and my daughter likes to watch baseball games too.'

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
cv.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.int64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': None,
 'min_df': 1,
 'ngram_range': (1, 1),
 'preprocessor': None,
 'stop_words': None,
 'strip_accents': None,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'vocabulary': None}

In [3]:
output = cv.fit_transform([text])
output.toarray()

array([[1, 2, 1, 2, 2, 2, 2, 1, 2, 1]], dtype=int64)

In [4]:
cv.vocabulary_

{'my': 5,
 'wife': 9,
 'likes': 4,
 'to': 6,
 'watch': 8,
 'baseball': 1,
 'games': 3,
 'and': 0,
 'daughter': 2,
 'too': 7}

- 불용어(Stopwords) 처리

In [5]:
# 직접 지정
my_stopwords = ['my', 'to', 'and']
cv = CountVectorizer(stop_words=my_stopwords)
output = cv.fit_transform([text])
output.toarray()

array([[2, 1, 2, 2, 1, 2, 1]], dtype=int64)

In [6]:
cv.vocabulary_

{'wife': 6,
 'likes': 3,
 'watch': 5,
 'baseball': 0,
 'games': 2,
 'daughter': 1,
 'too': 4}

In [7]:
# SciKit-Learn에서 제공하는 불용어 사용
cv = CountVectorizer(stop_words='english')
output = cv.fit_transform([text])
output.toarray()

array([[2, 1, 2, 2, 2, 1]], dtype=int64)

In [8]:
cv.vocabulary_

{'wife': 5, 'likes': 3, 'watch': 4, 'baseball': 0, 'games': 2, 'daughter': 1}

- 인덱스에 해당하는 단어를 알려주는 함수

In [9]:
# voca의 형태는 딕셔너리
voca = cv.vocabulary_
for key, value in voca.items():
    print(key, value)

wife 5
likes 3
watch 4
baseball 0
games 2
daughter 1


In [10]:
def get_word(index, voca):
    for key, value in voca.items():
        if value == index:
            return key
        
get_word(4, voca)

'watch'

##### 2. TF-IDF(Term Frequency - Inverse Document Frequency) Vectorizer

In [11]:
text = ['My wife likes to watch baseball games and my daughter likes to watch baseball games too.',
        'My wife likes to play baseball.']

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer(stop_words='english')
output = tv.fit_transform(text).toarray()
output

array([[0.38649245, 0.27160082, 0.54320165, 0.38649245, 0.        ,
        0.54320165, 0.19324622],
       [0.44832087, 0.        , 0.        , 0.44832087, 0.63009934,
        0.        , 0.44832087]])

In [14]:
tv.vocabulary_

{'wife': 6,
 'likes': 3,
 'watch': 5,
 'baseball': 0,
 'games': 2,
 'daughter': 1,
 'play': 4}

##### 3. N-gram

In [15]:
text = ['Machine learning is fun and not boring.', 'Machine is boring and learning is not fun.']

In [21]:
cv = CountVectorizer(stop_words='english', ngram_range=(1, 2))
cv.fit_transform(text).toarray()

array([[1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 1, 1, 0, 1, 1, 1, 1, 0]], dtype=int64)

In [19]:
cv.vocabulary_

{'machine': 3, 'learning': 2, 'fun': 1, 'boring': 0}

##### 4. Hyper Parameter

In [22]:
tv.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.float64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': None,
 'min_df': 1,
 'ngram_range': (1, 1),
 'norm': 'l2',
 'preprocessor': None,
 'smooth_idf': True,
 'stop_words': 'english',
 'strip_accents': None,
 'sublinear_tf': False,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'use_idf': True,
 'vocabulary': None}